name: CI
on: 
  pull_request:
    branches:
      - develop
jobs:
  flutter-test:
    name: Run flutter tesst and analyze
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: truongngo99/flutter-movies@v1
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test